### ISSUE TITLE
https://explorer.namecoin.info not showing new name ops

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#14]
The block explorer stopped showing new name ops after block 209965.  Any idea what's wrong?
##

**Comment by phelixbtc** [comment]
I updated the client to the latest version a while ago. Maybe the old one was a special compile or something. Need to look at how the explorer works...

**Comment by JeremyRand** [comment]
Since this is not getting fixed anytime soon (none of the current Namecoin developers has any familiarity with Khal's explorer code), and since any future explorer development would probably be better done on a free software implementation (AFAIK Khal's explorer is non-free), I'd like to shut off the explorer.  Luke-Jr informed me a while back that this explorer is ranking highly in Google (I guess because it's a subdomain of a popular 2nd-level domain), and it's extremely confusing to see outdated name data show up highly in search results.

If anyone has any objections to me shutting off https://explorer.namecoin.info , please make your objections known here in the next week.  @domob1812 @brandonrobertz @josephbisch @cassiniNMC @hlandau @jonasbits @midnightmagic

**Comment by cassiniNMC** [comment]
No objections. I'll miss https://explorer.namecoin.info/stats/block_count.txt though. It has been a very reliable means of double-checking my local getblockcount info. Anyone knows of a similarly easy-to-retrieve external _getblockcount_ API?

**Comment by JeremyRand** [comment]
@cassiniNMC:

> I'll miss https://explorer.namecoin.info/stats/block_count.txt though. It has been a very reliable means of double-checking my local getblockcount info. Anyone knows of a similarly easy-to-retrieve external getblockcount API?

I don't know of one, although I wouldn't be surprised if Insight could do it.  (@brandonrobertz ported Bitcore to Namecoin, so porting Insight would probably be straightforward.)

**Comment by JeremyRand** [comment]
> I'd like to shut off the explorer.

The explorer should now be shut off, and the various VirtualHosts that it used should now redirect to https://www.namecoin.org/explorers/ .  Let me know if anything is broken.
