### ISSUE TITLE
Twitter account should state that it is official.

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#17]
There are still apparently people thinking that Sudo's scam Twitter account is official.  It's not a productive use of my time or anyone else's to correct all such instances.

Right now the description of our account (@Namecoin) is:

"Building a censorship free web using Bitcoin technology."

We should change this to something like:

"Building a censorship free web using Bitcoin technology.  This official account is controlled by the Namecoin developer team."

Any objections to this?  @indolering

**Comment by indolering** [comment]
ACK

**Comment by JeremyRand** [comment]
Fixed.
