### ISSUE TITLE
Make Travis CI bot notify on #namecoin-dev when builds fail

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#20]
So apparently Namecoin Core has been broken sometimes on the Travis CI build, and I hadn't noticed.  I would suggest having Travis CI notify on #namecoin-dev when a build fails (for any Namecoin repo that has Travis CI enabled).  This seems to be fairly common practice among open source projects, and Travis CI supports this.

Thoughts?

**Comment by domob1812** [comment]
I don't think that's an important thing - isn't there something like subscribing to email notifications?  But I also do not oppose, if you (and others) prefer to hang out in IRC.

Note that the breakages are, as far as I can tell, nothing "critical" (i. e., it builds and works fine for me, including all unit and regression tests on my system).  Bitcoin itself broke it some times, and it seems to be failing on some systems only now.  But of course, if you think that you know how to fix it, that would be good.

**Comment by JeremyRand** [comment]
My preference is to use IRC instead of email because if something breaks while I'm away, and then gets fixed, I don't want to have my email full of notifications.  IRC is somewhat more ephemeral, which seems more appropriate to me.

**Comment by domob1812** [comment]
Ok.  Feel free to set it up then.

**Comment by josephbisch** [comment]
No one seems to have done this, so I guess I'll submit a PR for this on namecoin/namecoin-core. I'll just do it to namecoin-dev on Freenode, because it should get mirrored by the mirror bots to the other channels on other networks and Gitter. I'll try the default template to start with and it can be changed if we don't like it.
