### ISSUE TITLE
P2P Namecoin SPV Client [$131]

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#27]
This issue can be closed by releasing an SPV client for the Namecoin network that is capable of making P2P Namecoin connections (i.e. not a server/client model).  The client does not need to support name operations, but it does need to expose an API which something like NMControl could connect to without too much difficulty.

Note that the underlying codebase is an important decision, and should be made by the community.  Please talk to us before you begin on this issue, to make sure that you're doing it in a way that can close the issue to our satisfaction.
##

**Comment by shawnpringle** [comment]
This has already been done.  See coinomi android wallet.

**Comment by JeremyRand** [comment]
Shawn Pringle:

> This has already been done.  See coinomi android wallet.

Since when is Coinomi P2P?  Last I checked they're using an Electrum server.

**Comment by shawnpringle** [comment]
So, are there electrum servers for namecoin?  Can we use them as dns servers for the bit TLD?

**Comment by JeremyRand** [comment]
Shawn Pringle:

> So, are there electrum servers for namecoin?  Can we use them as dns servers for the bit TLD?

There are several existing independent attempts to port Electrum server
to Namecoin.  None of them meet our security standards, nor do they
support name operations properly.

If anyone would like to fund some development work in this area, I'm
pretty sure that we could get an Electrum server and client ported in a
way that's reasonably secure and could be used for name lookups.

Cheers.

**Comment by shawnpringle** [comment]
So if Coinomi doesn't use electrum servers for altcoins then it either uses some set of electrum like servers or SPV.   If it does SPV, then is that secure enough?

**Comment by shawnpringle** [comment]
https://www.cryptocompare.com/wallets/coinomi/ According to Crypto Compare Coinomi uses SPV validation.  That closes this issue as far as I know.

**Comment by JeremyRand** [comment]
Shawn Pringle:

> https://www.cryptocompare.com/wallets/coinomi/ According to Crypto Compare Coinomi uses SPV validation.  That closes this issue as far as I know.  

Last I checked Coinomi is using a single Namecoin Electrum server run by
Coinomi, which doesn't support AuxPoW.  That's not SPV, and is also not P2P.

**Comment by JeremyRand** [comment]
Noting for the record that libdohj is a candidate for closing this
issue, pending a Namecoin developer other than me testing it.

**Comment by shawnpringle** [comment]
Go ahead.  My understanding or misunderstanding come from statements on the
web.  I had never read Coinomi relied on a special server.  I suppose one
of you inspected the source, didn't you?

Shawn

On Nov 1, 2016 3:34 PM, "JeremyRand" notifications@github.com wrote:

Noting for the record that libdohj is a candidate for closing this
issue, pending a Namecoin developer other than me testing it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/namecoin/meta/issues/27#issuecomment-257654009, or mute
the thread

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Shawn Pringle:

> Go ahead.  My understanding or misunderstanding come from
> statements on the web.  I had never read Coinomi relied on a
> special server.  I suppose one of you inspected the source, didn't
> you?

I'm not certain whether you're referring to the Coinomi or libdohj
source?  I looked at the Coinomi source code a while ago when I was
evaluating it.  That was a few months ago, so it's possible that
something has changed recently.

FWIW, Bitcoin.org states the following about Coinomi:

> This wallet relies on a centralized service by default. This means
> a third party must be trusted to not hide or simulate payments.
> 
> This wallet uses central servers which are able to associate your 
> payments together and log your IP address.

So, if Coinomi has adopted either SPV validation or P2P networking,
it's a sufficiently new development that Bitcoin.org hasn't noticed yet.

Regarding libdohj, we're looking for some people to test it out.  You
can find a beta release of the libdohj name lookup client here:

https://namecoin.org/download/betas/#lightweight-spv-bitcoinj-name-looku
p-client

Cheers.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYIC1MAAoJELPy0WV4bWVwKEcQAMg+j4xneSuyy8vLyW/o/hFg
9ooz4PMMnAbLsWXLgWwOA+1P67aJm3ZtTduw+SkWx/rIMngh44TKNTfXyyoysIBC
SX3JiErs9IxP1apRK+1ll5DuDO/aK6CiOx109eZiA8/an8hE9jEQPY1pGZf//B+2
tKJ2RlXOJXpzY9H8g1u1XZE1B1eYynh9aAbpWJe75ORjl2HhIiS2X3x3xRvYX0GU
AplAM+esCpYN7rLbhwwHUpH+F+WxLOkeXoxzSpvYYD+oGdEm4O3KiaIfqSTi1+2O
el558ndgBL0IgqQgP0FAuTALAeu0EWZntnnnBYWMk2F1TZahRiblJD3nlG1JPcIQ
k6ej8i9emJKEO7OPcKyD8eAfkhHmPN1v7/5Is5OgxQ0h+vxgyOWaY+SGYjCyKFfH
SneDnCstKxcGwrer7alT1s3pCqnztsXQBcONKOQanI7n5+c9VzeVGGTs8BaH2OH9
tTSeRDqCRUWBH3DHE9rcWRaqJVLAdp9+bfbMWsjUNPdEnlYcJyrgW7Q6d+0VOVc6
9bSN8t+VxHNcN5nhSLnM04j6NwcEYsOcHLVEYUBKO3Ob5W7eGCdsxyavMfbXwCtN
UmVvr5jQnOcnP6vqQwJ+2bJfIL8YLob3/h/Asm72TrrayuWOF5jJMxfjSM3mCYGp
Xew/6EYd2uxPmBaPzIEh
=lLaH
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
libdohj-namecoin and my consensusj fork have met the terms for closing this issue as fixed.

**Comment by JeremyRand** [comment]
Also noting for the record that Coinomi is not free software, which further disqualifies it from satisfying this issue.
