### ISSUE TITLE
Working https Certificates

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/meta#3]

**Comment by ryancdotorg** [comment]
This is now set up, and we get "A" grades from SSLLabs

https://www.ssllabs.com/ssltest/analyze.html?d=namecoin.org&hideResults=on
https://www.ssllabs.com/ssltest/analyze.html?d=namecoin.info&hideResults=on

Please allow 24 hours for DNS changes to namecoin.info to propagate.

**Comment by phelixbtc** [comment]
Sweet. Closing.
