### ISSUE TITLE
namecoin/meta repository spells "Purpose" wrongly. :-)

### ISSUE THREAD

**Issue by midnightmagic** [namecoin/meta#39]
n/t
##

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Fixed.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzk0HAAoJELPy0WV4bWVw5TgQAJ1Pu0Nh37ZAOb5+ft+mWz5b
+3JqV4gyC79SkenZh2qQHHHksYB3hJ5h+lOTBqgraKqwSMbTXDGfArmuPhQpHWSd
4xlg7d26vnY8cIPvB9GEQbVGET4KOXDSSnchNtoPmxLWsBJXqL5EMN/LrAiARrYJ
h97r2/Lhef5ea081F9GYXTrW1pLUBXQmUZjBqgBwbIxZUhJyO90IGGJfF3+YhRUd
JB/QPzwEFSGdttmj+57u0rJcsi22gSiKgUU66svH6IcZcRnE++EoVpWv8XGbmBO9
M94TixdRnalAD9NPq5IzQATsqzo0N58mQxXcNGC7zlo3rA/qrzO2rN+5lfV+FLAh
cxTWnkX64Z61PqtSORzVOsfi5oVBsIC/wYpcCCtvqMzaRF6NtwpAE3X2JDM2/Om5
gDYl1XmKwXFSA9wT+6wPzWAMQhLFsTUoFARpjp3oB13RwsxOD/z3Fvfddf1tJ5XZ
0ZutTOM753fmMkChg0eOofOminTUXKYiOYcDwYe9TaS9kr6E9DTM1lF4/CWB5pYC
WbULI8Ipgo1MQGh/kIVaNm8QONpd2vF4Xlxp2gY/Vx2mxnL06ms0Ynu4rQjzDFel
VROnvTeFNA0y+e7/Gzooa87x73Zk7hP0ETeuuK1MLPQ9KSqSYbMorWEJhUjQy4vg
FnLRGa9m6kxOCHAyQWRn
=XyAR
-----END PGP SIGNATURE-----
