### ISSUE TITLE
Reassign Tip4Commit donations

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#47]
4 of our deprecated repos have Tip4Commit donations [assigned to them](https://tip4commit.com/projects/search?utf8=%E2%9C%93&query=namecoin&order=balance).  I'd like to contact Tip4Commit admins and ask that those donations be reassigned as follows:

NMControl: split equally between ncdns and ncdns-nsis.
Convergence: split equally between ncdns, ncdns-nsis, and dns-prop279.
libcoin: split equally between Namecoin Core, Electrum-NMC, ElectrumX, libdohj, and bitcoinj-addons.
Namecoin-Legacy: reassign to Namecoin Core.

Doing this will have the benefit of allowing those funds to be disbursed (it's actually a decent chunk of money now thanks to the Bitcoin price increase).  It might also encourage a few spammers to send [low-quality PR's](https://github.com/namecoin/namecoin-legacy/pull/240) to those repos; I don't think this is a problem since we're under no obligation to merge PR's, and we're also under no obligation to release funds for commits that we don't think deserve funding (so spammers will be wasting their time on us).

Is it okay to do this?

**Comment by JeremyRand** [comment]
If no NACKs are received in 1 week, I'll assume it's okay to proceed.

**Comment by brandonrobertz** [comment]
ACK

**Comment by JeremyRand** [comment]
I've just contacted Tip4Commit, see https://github.com/tip4commit/tip4commit/issues/342

**Comment by JeremyRand** [comment]
Done.
