### ISSUE TITLE
ncdns NSIS installer

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#50]
(This ticket was defined on 2016 November 26, but I neglected to actually create the ticket on GitHub because I'm disorganized.)

Criteria for an NSIS installer in order to close the ticket:

* Modify Unbound configuration to use ncdns for .bit.
* Restart Unbound service.
* Install ncdns as a Windows service (as a user with minimal privileges).
* Optionally allow the user to enable ncdns TLS CryptoAPI support. If this is chosen, setup registry permissions to allow ncdns to access the root CA trust store, and provide the user with instructions for setting up an HPKP pin in Chrome for .bit.
* Hide the ncdns user from the login screen.
* Set up DNSSEC signing.
* Use the same compression and other build settings as Bitcoin Core uses, so that we can be confident that the NSIS installer will build reproducibly.
* Needs to be buildable from Linux, without binary blobs.

Ticket was assigned to @hlandau at the time it was defined.

**Comment by JeremyRand** [comment]
@hlandau Do you agree that this ticket's requirements have been met?

**Comment by hlandau** [comment]
I agree that the ticket's requirements have been met.

**Comment by JeremyRand** [comment]
Cool.  Confirming on my end that the bounty goes to @hlandau .  Closing as finished.
