### ISSUE TITLE
Email for NLnet submission

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/meta#56]
@domob1812 Is it okay if I list your email address as a contact for the NLnet proposals that I'm sending in later today?  Vincent's mail server is still partially broken and I don't want to risk email from NLnet getting dropped.

**Comment by domob1812** [comment]
Yes sure, assuming I'm only a second contact and/or I will know what to do when I get an email.

**Comment by JeremyRand** [comment]
Thanks @domob1812.  I ended up using an old Gmail address of mine that's configured to auto-forward to Vincent's mail server.  Experimental testing reveals that for some reason, auto-forwards from Gmail to Vincent's server seem to be delivered fine.  If that method ends up running into problems, I'll tell NLnet to use your address as a fallback.
